site: Soul Lee
url: https://soulee.dev
title: Soul Lee
description: Developers can change the world

author:
  name: soulee
  avatar:
  email: alus20x@gmail.com
  url: #yoururl
permalink: pretty

# --- SEO SETTING ---
lang: ko_KR
twitter:
  username: #
  card: summary

facebook:
  app_id: #
  publisher: #
  admins: #

# --- SEO SETTING ---

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

paginate: 5
paginate_path: "/page:num/"
