name: Pagespeed Insights Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1.1
        id: psi
        with:
          url: "https://soulee.dev"
          threshold: 70
          strategy: mobile
